TRUTH = (
    "❔ Sual: İtirməkdən qorxduğunuz tək şey nədir?",
    "❔ Sual: Bu an kimisə bəyənirsiniz?",
    "❔ Sual: Qısqanc olduğunuz ən yaxşı dostunuzla bağlı bir şey var?",
    "❔ Sual: Zəngin bir oğlan üçün sevgilinizə xəyanət edərdinizmi?",
    "❔ Sual: Ən böyük fikriniz nədir?",
    "❔ Sual: Valideynlərinizə son dəfə nə vaxt yalan danışdınız və niyə?",
    "❔ Sual: İdeal dostunu təsvir edin.",
    "❔ Sual: Etdiyiniz ən qorxunc şey nədir?",
    "❔ Sual: Müsabiqədə iştirak etmək üçün yaşınız barədə heç yalan danışmısınızmı?",
    "❔ Sual: Heç kimisə izlərkən tutuldunuzmu?",
    "❔ Sual: Səni ən çox əsəbləşdirən şey?",
    "❔ Sual: Sizcə virtualda dostluq var?",
    "❔ Sual: Aldığın ama əsla istifadə etmədiyin 5 mənasız şey nədir?",
    "❔ Sual: Əgər indi bir arzunuzun yerinə yetirilməsinə vəd versələr, nə arzu edərdiniz?",
    "❔ Sual: Başqalarının məsləhətlərini dinləyirsiz?",
    "❔ Sual: Bir diş fırçasını ən yaxşı dostunuzla bölüşərdinizmi?",
    "❔ Sual: İlleqal yolla puz qazanmaq üçün hansı yolu seçərdin?",
    "❔ Sual: Ən vacib hədəfinizlə aranızda məsafə yaradan maneə nədir? Bir sözlə ifadə edin.",
    "❔ Sual: İçində ölüm tarixinin yazılı olduğu bir zərf alsaydın,açıb baxardınmı?",
    "❔ Sual: Həyatındakı ən gözəl gün necə olub?",
    "❔ Sual: Digər insanlardan fərqli olaraq nələr edirsən?",
    "❔ Sual: Sosial keçmişini biri görsə utandigin şey nə olardı?",
    "❔ Sual: Etdiyin hansı səhvi bir də təkrar etməmisən?",
    "❔ Sual: “Yox“ demək istədiyiniz halda tez-tezmi “hə” deyirsiniz? Bunun səbəbi nədir?",
    "❔ Sual: İnstaqramda bir məşhur sizi təqib etsəydi, bu məşhurun kim olmasını istərdiniz?",
    "❔ Sual: Xəyalınızdakı toy necədir?",
    "❔ Sual: Ən uzun münasibətiniz(sevgi) nə qədər olub?",
    "❔ Sual: qrupdakı userlərdən kimləsə kimsəsiz adaya düşməli olsan kimi seçərdin?",
    "❔ Sual: Heç ayıb bir şey edərkən yaxalanmısan?",
    "❔ Sual: Unutmaq istədiyin xatirən?",
    "❔ Sual: Heç kimin tapa bilməyəcəyi pis bir şey etdiniz?",
    "❔ Sual: Heç ilk görüşdə aşiq oldunmu?",
    "❔ Sual: 24 saat yaşamağınıza vaxt qalsaydı və bu qrupdakı hər kəslə bir şey edə bilsəydiniz, kim olardı və o adamla nə edərdiniz?",
    "❔ Sual: Səbəbsiz yerə ağlamısanmı?",
    "❔ Sual: Tanımadığın bir insan görəndə ilk öncə onda nəyə diqqət yetirirsən?",
    "❔ Sual: Etdiyiniz nələr ilə fəxr edirsiniz?",
    "❔ Sual: Yaxın vaxtlarda hansı xeyirxah əməli etmisiniz?",
    "❔ Sual: Başqası üçün aldığın ən ucuz hədiyyə nə idi?",
    "❔ Sual: Ən sevdiyin serial?",
    "❔ Sual: Yerində olmaq istədiyiniz məşhur hansıdır?",
    "❔ Sual: Sevib acı çəkərək yaşamağ ya qırağdan izləyib xoşbəxt olmaq?",
    "❔ Sual: Sən hansısa bir qeyri-adi bacarığının olmasını istəyirsən?",
    "❔ Sual: Sevdiyiniz oğlan və ya qız əkscinsi ilə danışsa, nə edərsiniz?",
    "❔ Sual: Qrupdakılarla görüş keçirilsə, gələrdin?",
    "❔ Sual: Şiddətə meyillisinizmi?",
    "❔ Sual: Kin saxladığın yada sildiyin biri olub? Olubsa, səbəbini yaz.",
    "❔ Sual: Cansız varlıq olsan, hansı varlıq olmaq istəyərdin?",
    "❔ Sual: Əgər başqa cür insan olmaq şansınız olsaydı, necə birinə çevrilərdiniz?",
    "❔ Sual: Bədənində dəyişdirmək istədiyin bölgə varmı ?",
    "❔ Sual: Darıxdığınız, amma əlaqə qura bilmədiyiniz biri varmı? Varsa, kimdir?",
    "❔ Sual: Həyatınızdakı ən gözəl gün necə olub? Və niyə belə düşünürsünüz?",
    "❔ Sual: Adını dəyişsəydin, nə qoyardın?",
    "❔ Sual: Əgər bu gün ölsəniz, insanlar sizin barədə nələr deyəcəklər?",
    "❔ Sual: Mahir rəqqas olmağı seçərdiniz, yoxsa peşəkar riyaziyyatçı olmağı?",

    

  
)

DARE = (
    "Ay göy-ala qarğa qardaş, mənimlə qardaş olsan da səninlə qardaş olacağam, olmasan da səninlə göy-ala qarğa qardaş olacağam. (səsli at)"
    "Son mesaj yazdığının dostun mesajlarında nə dediyini göstərin",
    "Qrupdan kiməsə Instagram hesabınızdan kimsə DM verin",
    "Çiy bir sarımsaq ye,foto at",
    "Bir buz kubunu əriyənə qədər ağzınızda saxlayın(foto at)",
    "Qrupdakı bir şəxsə iyrənc bir şey söyləyin!",
    "Mövcud 3 müxtəlif mayeyi bir stəkana qoyun və için",
    "Ağlınıza gələn ilk sözü bağırın",
    "Bir qaşıq ketçup yeyin(foto at)",
    "Telefon kitabçanızdakı son şəxsi ss atın",
    "Cazibədar bir banan yeyin",
    "Cüzdanınızı / çantanızı boşaldın və içərisində olanları hamıya göstərin",
    "Əllərinizi istifadə etmədən yemək yeyin",
    "Qrupdakı istədiyiniz insan haqqında iki dürüst şey söyləyin",
    "Mümkün qədər tez qrupu güldürün",
    "Bütün yumruğunuzu ağzınıza qoymağa çalışın",
    "Hər kəsə özünüz haqqında utandırıcı bir hekayə danışın",
    "Dirsəyinizi öpməyə çalışın",
    "İnstagram hekayələrində telefonunuza ən köhnə selfini göndərin",
    "Bildiyiniz ən kədərli hekayəni danışın",
    "Bir dəqiqə canavar kimi ulu",
    "Pəncərəyə çıx və kömək edin deyə qışqır",
    "Gözlərinizi çəpləşdirərək şəkil çəkin və qrupa atın.",
    "Çölə ən sevdiyin əşyanı at, videosunu çəkib qrupa at",
    "İnstagram,Telegramda-da ən sonuncu dostluq göndərən birinə səndən xoşum gəlir yaz.",
    "Ən son yazı olan Whatsapp qrupuna Sizdən bezdim day, çıxın həyatımdan  yaz və qrupdan çıx.",
    "Atana yaz Ata, məni o günkü kimi döy də, darıxmışam lap de, atanın cavabını səsə yazıb qrupa at.",
    "Qalereyanızın ekran görüntüsünü göndərin.",
    "Whatsapp dərs qrupunda başdan 7, ya da 8-ci adama, Baxışlarında dərin məna var, bunu isə yalnız mən görə bilirəm de və ss edib qrupa at.",
    "Ən gözəl və sevilən şəkilinizi atın",
    "Qrupa ❤️ emojisi at. Bu mesajdan sonra mesaj yazan ilk şəxsə şəxsidən 5 dənə ❤️  göndər, ss edib qrupa at",
    "Əlifbanı tərsdən sıra ilə de(ses at)",
    "Əlinə qələm ilə, MAL yazıb şəklini qrupa at",
    "Cücələrim, mahnısını oxu və səs olaraq qrupa at",
    "Səni deyirlər, mahnısını oxu, səsini qrupa at",
    "Qalereyanızın ekran görüntüsünü göndərin.",
    "İnək kimi Möö et, səsini qrup at.",
    "Google'da axtarış keçmişinə gir, ss elə at(silme eşşək😂)",
)
